@section('BODY')
    @include('nabre-quickadmin::skeleton.widget.navbar')
    @section('CONTAINER')
        @include('nabre-quickadmin::skeleton.widget.breadcrumbs')
        @include('nabre-quickadmin::skeleton.widget.title')
        @include('nabre-quickadmin::skeleton.widget.yeld',['YELD'=>'CONTENT'])
    @endsection
    @include('nabre-quickadmin::skeleton.widget.container')
@endsection
